### ISSUE TITLE
Original PCAPs

### ISSUE THREAD

**Issue by JordanHolland** [ACANETS/NetML-Competition2020#2]
Hi @onurbarut,

I'm attempting to rebuild the NetML dataset from the paper (built from the Stratosphere IPS data). I had assumed that Table 2 in the paper would lead me to the correct traces, but I'm unable to find those specific files (PCAPs) on the Stratosphere website. Am I missing something, or do you have a mapping from the `filename` column in Table 2 to the PCAP trace from Stratosphere?

Thanks!

**Comment by onurbarut** [comment]
Hi, check these files: https://www.stratosphereips.org/datasets-malware search for the malware type, click on the link and see the pcap filename. They should match.

Let me know if you need further info.

Onur

**Comment by JordanHolland** [comment]
Ah, just had to dig a bit further. 

Thanks for the quick response
