### ISSUE TITLE
Recreating traffic flows

### ISSUE THREAD

**Issue by JordanHolland** [ACANETS/NetML-Competition2020#3]
Hi @onurbarut,

Sorry to bother again, and thanks again for your help earlier. I'm attempting to recreate the raw traffic flows for which the features were extracted for netML. Using a flow separator on the PCAPs for the netML dataset generated a significantly different number of samples than in the arXiv paper, so I believe i'm doing something wrong. 

My goal is to end up with a set of PCAPs labeled with what's in the file, such as:
`toplabel_finegrainedlabel_sample_n.pcap`

Examples:

`malware_bitcoinminer_sample1.pcap`
`benign_benign_sample50000.pcap`

I have the raw traffic from `table 2` in the paper extracted into flows, but I seem to be missing a filtering step as the number of flows extracted is extremely high. 

Thanks for any and all help!

Jordan

**Comment by onurbarut** [comment]
Hi @JordanHolland , can you provide more information, i.e. numbers and method of extraction so that I can help better.

Onur

**Comment by JordanHolland** [comment]
Thanks for the quick response.

I started by using [pkt2flow](https://github.com/caesar0301/pkt2flow), which separates flows into files marked by the 5-tuple and the timestamp the flow started. I also included UDP and non-UDP/non-TCP flows. The options I used are listed below.

>   -u      also dump (U)DP flows7
>   -v      also dump the in(v)alid TCP flows without the SYN option
>   -x      also dump non-UDP/non-TCP IP flows

I'll start with the Sality capture, which is 2.1 GB ([file location for reference)](https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-319-1/)

Number of tcp_syn flows: 5,188,978
Number of UDP flows: 2,341,792

There are also "other" flows (ICMP, etc) which I'll not list.

A few questions:
1. Are you only considering TCP flows?
2. Are you including IPv6?
3. Are you dropping any flows? (i.e. flows that don't contain HTTP / TLS / DNS)?

A few more examples of the numbers i'm getting:

Malware| tcp_syn | udp       | "other"
Artemis           | 10253    |  36669 | 1019
Adload            | 38          | 28768   | 57520
Ursnif              | 10559    | 37743   | 1082

I'm happy to use other means to split the flows up, such as the popular [PcapSplitter](https://github.com/seladb/PcapPlusPlus/tree/master/Examples/PcapSplitter)

Ultimately, I'd like to reproduce the labeled flows for each dataset in the paper, so figuring out how to split them to match yours would be great.

Thanks again for your quick response and help, let me know if you need anything else on my end.

Jordan

**Comment by onurbarut** [comment]
@JordanHolland , we consider only TCP (TCP+X, TCP+HTTP, TCP+TLS) and UDP (UDP+X, UDP+DNS) flows. "X" means any other protocol that we do not extract feature but we use those flows to extract metadata features from TCP/UDP headers.

Most important differences between our method and pkt2flow might be that:
1- we do not implement any timeout for the flows. We only categorize the flows by matching the five-tuple (IP.src, IP.dst, src_prt, src_dest, proto). Some other implementations may want to separate flows from a single five-tuple by implementing flow time-out.
2- our definition of "flow" is bi-directional, i.e. forward and backward traffic is combined to form the flow. Some other researchers may prefer to call this bi-directional traffic as "session" and they treat forward and backward traffic as separate flows. 

I hope these will help you. Let me know if you need further info.

Onur

**Comment by JordanHolland** [comment]
This helps. To summarize and make sure we're on the same page, a flow would be summarized as

1. any TCP or UDP flow, using the 5-tuples, considering flows as bidirectional traffic.


Also, just to ask, is the flow-separation code public? To be clear, not the feature extraction, just the code that splits up flows. 

Thanks again for your help, things are clearing up on my end!

**Comment by onurbarut** [comment]
We perform feature extraction and flow separation in the same library, so unfortunately that's not public, yet.

Yes, flow is a tcp or udp (ipv4) bi-directional traffic of same 5-tuples.

**Comment by JordanHolland** [comment]
No problem, I understand. This has all been incredibly helpful, thanks again for your time. I'll update you if I have any issues.

Jordan

**Comment by JordanHolland** [comment]
Hi,

I've been able to run flow-extraction on some of the files in the netML dataset. Many of the ones I have processed we match exactly in the number of samples from the raw traffic. One significant difference is the `sality` malware file, which is 2.1GB. I downloaded the file from [here](https://mcfp.felk.cvut.cz/publicDatasets/CTU-Malware-Capture-Botnet-319-1/), matching filenames in the paper. The table shows 39 labeled samples, while I'm getting 98,434. This makes some sense, as the file is 2.1GB, significantly larger than many of the others. 

Any chance I downloaded the wrong file?

Thanks!

**Comment by onurbarut** [comment]
Hi Jordan,
Thanks for the update! We will check out your point and let you know what might happened with Sality. Best.

**Comment by JordanHolland** [comment]
Hi @onurbarut,

Attempting to recreate the netML IDS dataset, but having some trouble due to the process being a bit more confusing than the other two. Could you explain how you extract the flows in a bit more detail?

Do you:
1. extract the time of attack from the entire PCAP
2. extract every flow in that time window?

Or:

1. extract the time of attack from the entire PCAP
2. extract flows from specific IPs in that time window

<img width="823" alt="Screen Shot 2021-01-19 at 5 52 50 PM" src="https://user-images.githubusercontent.com/10257554/105103846-43d04080-5a7f-11eb-998c-8239bbfa9a2b.png">


For example, what was the process for extracting flows from the Tuesday capture, which involves the NAT process.

Thanks again for all of your help, the other 2 datasets were much easier with your guidance!

**Comment by onurbarut** [comment]
Hi @JordanHolland , that's a great question. As explained in CICDIDS 2017 website, the flows of interest are specified in certain time interval between the given IPs. Therefore, we first extract the flows within the time interval, then extract the flows for the specified IPs in source and destination in that time interval.

**Comment by JordanHolland** [comment]
@onurbarut, this starts to clear some things up. One more question, when you say the specified IPs in source and direction, do you mean each pair above? i.e.:

src: 205.174.165.73 dst: 205.174.165.80
src: 205.174.165.80 dst: 172.16.0.10
src: 176.16.0.10 dst: 192.168.10.50

Or do you only select one of src, dst tuples above for the attack traffic?

Thanks again for your help, hopefully it hasn't been too much trouble

**Comment by onurbarut** [comment]
For example let's consider tuesday traffic here: https://www.unb.ca/cic/datasets/ids-2017.html

To extract FTP-patator traffic, 

1- We first extract all the flows in the time interval (9:20 – 10:20 a.m.).
2- Then, we use this time window traffic and extract and keep the flows between the attacker and victim(s) IP(s) and label them as FTP-patator. We discard other flows in this time window.

**Comment by JordanHolland** [comment]
This makes sense. The weird part is that in the Tuesday traffic I don't see a single packet from the "attacker IP" if attacker IP is considered 205.174.165.73.

`tcpdump -r Tuesday-WorkingHours.pcap src 205.174.165.73`

does not print out a single packet from the source (which is the "attacker" for the day). I've checked the md5 hashes and my traffic file matches the one on the website.

**Comment by onurbarut** [comment]
Yes, I had a lot of trouble trying to understand and correctly parse the flow of interest in this dataset. I remember I ran into the same situation with you. Then I checked the IPs in the NAT process and I found that one of them (cannot remember which)  actually existed in the pcap file. Please try to search for other IPs and I am sure you will get hit. Let me know if it didn't work.

**Comment by JordanHolland** [comment]
Hey @onurbarut, 

Thanks for the response.

I actually went through the same process as you and was able to match your dataset numbers as of a few minutes ago, really weird process but it does have to do with the NAT IPs. 

Thanks again for all of your help.
