### ISSUE TITLE
NetML Competition 2020 Results

### ISSUE THREAD

**Issue by Narayan2407** [ACANETS/NetML-Competition2020#4]
Hello Sir @onurbarut
I am a member of the **Team01_5C_2020_SoCSE_KLETech** team and we have participated in the NetML Competition 2020 and we were wondering when will the results be announced. As said earlier in the competition overview page, the results were supposed to be announced on January 7th but there was no update on it so we wanted to know about the details and the platform where the results will be announced. Thank You.

Best Regards,
Narayan Kulkarni

**Comment by onurbarut** [comment]
We thank all the participants for attending the NetML Competition 2020. The results are announced in the challenge evaluation website: https://eval.ai/web/challenges/challenge-page/526/overview 

We appreciate your patience and hope to see you next year in NetML Competition 2021!

**Comment by Narayan2407** [comment]
Thank You so much for the details, can we have the list of top 3 winners in each of the 7 tracks.
That would be great.

With Regards,
Narayan Kulkarni
